name = "Baby It's Cold Outside"
author = "Vigilante"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a7c8bb5d3afcc0127f360a48f11c11e3acbb7a7f19d2896ae7cc1a38d717c99"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
