name = "Baby It's Cold Outside"
author = "Vigilante"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1afd8c5859060b8d521166ad0967d747373a5a494dc515183223cc65552f23e9"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
