name = "Baby It's Cold Outside"
author = "Vigilante"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c29564033d1ee1db10fd71de4b4a301598a0e49a61e92a4ff2abf7bdac133b0"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
