name = "Baby It's Cold Outside"
author = "Vigilante"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfc1a273c9a464ed7286bb55c8d287f49bfb96b4973ce2354aafa6e31b24b8d6"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
